# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Car Picker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Car Picker
  pod 'Starscream'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire'

  # CI/CD
  pod 'AppCenter'


  # Testing
  pod 'Quick'
  pod 'Nimble'

  target 'Car PickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
