# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Car Picker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Car Picker
  pod 'Starscream'
  
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire'

  #RX
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxStarscream'

  # CI/CD
  pod 'AppCenter'


 
  target 'Car PickerTests' do
    inherit! :search_paths
    # Testing
    pod 'Quick'
    pod 'Nimble'
  end

end
